### ISSUE TITLE
Out of memory while training large data

### ISSUE THREAD

**Issue by xuelianl** [hnlab/FAST#2]
**Problem**: training SG-CNN model on large data set needs enormous memory, which we can't afford, so we need to decrease the memory used.   

**Detail description**
- while training first epoch, the memory used will increase gradually, then maintain at the highest;   
![Screenshot from 2021-09-14 16-18-36](https://user-images.githubusercontent.com/54713559/133221990-790742a3-8f2b-48d2-8f4c-1cf6d3b76eb4.png)
- when trained on large data set(160,000 entries), the task will be killed due to out of memory.   
![Screenshot from 2021-09-14 16-19-30](https://user-images.githubusercontent.com/54713559/133222110-1f3ddb7d-a435-476f-ad50-999987fc4801.png)

**Script**: [train_reduce_valid.py](https://github.com/hnlab/FAST/blob/xll_sgcnn/SG-CNN/PDBbind_v2019/2-train/train_reduce_valid.py)
@0ut0fcontrol

**Comment by zhuhui-in** [comment]
起初potentialnet使用multiprocessing load graphs, 在加载图片的时候就会爆内存，后来改为单线程加载不存在内存问题，我昨晚试了一下，potentialnet 17w 数据完全没有问题，根据内存的比例我这边可以train 30w+的数据（但是太慢了，构建graph+跑完一次估计24小时）。fcnn和potentialnet的模型代码十分类似,我可以试着看看两者的代码的区别，看看哪里出了问题。
  @0ut0fcontrol @xuelianl 
![image](https://user-images.githubusercontent.com/69226545/133351458-1b360d85-87c2-46af-87f9-9287b988ef7c.png)

**Comment by 0ut0fcontrol** [comment]
@zhuhui-in 好，你看看是不是有多进程worker。

fast是在训练过程中，随batch数增加内存逐渐增加。
感觉像是没有detach，导致计算图在内存中累积。

我下午按这个博文去debug，有进展及时沟通。

Memory Leakage with PyTorch
https://medium.com/@raghadalghonaim/memory-leakage-with-pytorch-23f15203faa4

**Comment by 0ut0fcontrol** [comment]
@xuelianl 
cc @zhuhui-in 
内存暴涨是因为缓存了特征化后的数据。
https://github.com/hnlab/FAST/blob/b334ab63358eff3ac8edce556bb1c605cd949514/model/sgcnn/src/sgcnn/data_utils.py#L92-L107

使用`PDBBindDataset(cache_data=False)`, 内存占用变得很小，但耗时会增长为原来的4倍。

使用多（4或8）个worker、使用本地存储（/tmp，而不是网络存储(/pubhome)），都没有加速。

可能是worker数还不够多（原代码使用24个worker），也可能是都去读同一个hdf5文件，有IO竞争。


详细测试结果见 https://github.com/hnlab/debug_llnl_fast

可能解决策略：
1. 使用更多的worker。
1. 数据集分成多个hdf5文件。
1. 缓存特征化后的数据集到disk。

另外，如果要真正随机batch，要注意把[`worker_init_fn()`](https://github.com/hnlab/FAST/blob/b334ab63358eff3ac8edce556bb1c605cd949514/model/sgcnn/src/sgcnn/train.py#L102-L103)替换为[`seed_worker()`](https://pytorch.org/docs/stable/notes/randomness.html#dataloader)。
现在的`worker_init_fn()`使每个epoch的seed都是0,  每个epoch产生的batch应该是一样的。

**Comment by xuelianl** [comment]
经金才师兄@0ut0fcontrol测试，发现SG-CNN在处理图时的不合理之处：

> 在将分子转为图的时候，只生成相邻（e.g. dist<6 A）的原子（节点）的边，图所需的内存就会显著缩小。
> 
> 在LLNL/FAST中，几乎生成了所有原子间的边，所以图需要的内存才会这么大！这是不合理的。

并提出了改进方法，见https://github.com/hnlab/debug_llnl_fast/blob/58c3325ae23d95ad23554d37462d12771aa66f5b/2-train/data_utils.py#L186

以下为我分别使用**禁用缓存**以及去除原子距离大于7.5的边(**modify_dists**)两种方法训练数据集的测试结果。
- 在禁用缓存后，在PLANet_all (N=162178)数据集中可成功进行训练，所需的最大内存由300G降为8G，但是训练时间长达8天；
- 不禁用缓存，只modify_dists后，在PLANet_all (N=162178)/PDBbind_v19_general_set 数据集中进行训练，所需的最大内存大约变为原来的1/5，PDBbind训练所需时间变为原来的3/5；对结果似乎没有明显影响。

基于上述结果，最终选择**modify_dists**的方法用于训练SG-CNN模型。
具体测试结果见: https://nibs-beijing.feishu.cn/sheets/shtcntSXGdX0LTgh0HOwf0tMtlf
关于该issue的更多讨论见飞书的话题群`#问题# #DL# PyTorch如何处理大规模蛋白-配体数据集`
